apiVersion: v1
kind: ServiceAccount
metadata:
  name: visualpath
  namespace: visualpath

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: mynamespace-user-full-access
  namespace: visualpath
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["pod", "deployment", 'configmap']
  verbs: ["get", "create"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: mynamespace-user-view
  namespace: visualpath
subjects:
- kind: ServiceAccount #user, group
  name: visualpath
  namespace: visualpath
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mynamespace-user-full-access